/**
 * Typed surface of the database, for both clients.
 *
 * `database.types.ts` in this folder is GENERATED by `npm run db:types` and is
 * never hand-edited — if a type looks wrong, fix the migration and regenerate.
 *
 * This file is the hand-written part: convenience aliases so call sites read as
 * `Venue` rather than `Database['public']['Tables']['venues']['Row']`.
 */

import type { Database } from './database.types.js';

export type { Database } from './database.types.js';

export type Schema = Database['public'];

export type Tables<T extends keyof Schema['Tables']> = Schema['Tables'][T]['Row'];
export type Insertable<T extends keyof Schema['Tables']> = Schema['Tables'][T]['Insert'];
export type Updatable<T extends keyof Schema['Tables']> = Schema['Tables'][T]['Update'];
export type Enums<T extends keyof Schema['Enums']> = Schema['Enums'][T];
export type FunctionArgs<T extends keyof Schema['Functions']> = Schema['Functions'][T]['Args'];
export type FunctionReturns<T extends keyof Schema['Functions']> =
  Schema['Functions'][T]['Returns'];
